class BaseConstants:
    get_method_str: str = "get"
    error: str = "error"
    code: str = "code"
    status: str = "status"
    data: str = "data"
    symbol: str = "symbol"
    interval: str = "interval"
    currency_name: str = "currency_name"
    desired_price: str = "desired_price"
    return_channel_name: str = "return_channel_name"
    timestamp: str = "timestamp"
    price_range: str = "price_range"
